/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhir;

import java.util.ArrayList;
/**
 *
 * @author Lenovo
 */
public class TugasAkhir extends javax.swing.JFrame {

    private String JenisKelamin;
    private String PTKPStat;

    /**
     * Creates new form TugasAkhir
     */
    public TugasAkhir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        Data = new javax.swing.JPanel();
        Nama1 = new javax.swing.JLabel();
        IsiNama1 = new javax.swing.JTextField();
        Gaji1 = new javax.swing.JLabel();
        IsiGaji1 = new javax.swing.JTextField();
        Perusahaan1 = new javax.swing.JLabel();
        IsiPerusahaan1 = new javax.swing.JTextField();
        Status1 = new javax.swing.JLabel();
        PilihStatus1 = new javax.swing.JComboBox<>();
        NPWP1 = new javax.swing.JLabel();
        IsiNPWP1 = new javax.swing.JTextField();
        Kelamin1 = new javax.swing.JLabel();
        PilihKelamin1 = new javax.swing.JComboBox<>();
        Iuran1 = new javax.swing.JLabel();
        IsiIuran1 = new javax.swing.JTextField();
        Tunjangan1 = new javax.swing.JLabel();
        IsiTunjangan1 = new javax.swing.JTextField();
        Jabatan1 = new javax.swing.JLabel();
        IsiJabatan1 = new javax.swing.JTextField();
        Anak1 = new javax.swing.JLabel();
        IsiAnak1 = new javax.swing.JTextField();
        JudulData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Saudara1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Hasil = new javax.swing.JPanel();
        Pekerjaan = new javax.swing.JLabel();
        PKP = new javax.swing.JLabel();
        Persen = new javax.swing.JLabel();
        PTKP = new javax.swing.JLabel();
        WPajak = new javax.swing.JLabel();
        Bersih = new javax.swing.JLabel();
        NPWP = new javax.swing.JLabel();
        JPajak = new javax.swing.JLabel();
        JudulHasil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TitikDua1 = new javax.swing.JLabel();
        JPajak3 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        Bersih1 = new javax.swing.JLabel();
        PKP3 = new javax.swing.JLabel();
        WPajak1 = new javax.swing.JLabel();
        TitikDua6 = new javax.swing.JLabel();
        TitikDua7 = new javax.swing.JLabel();
        TitikDua9 = new javax.swing.JLabel();
        JPajak1 = new javax.swing.JLabel();
        TitikDua8 = new javax.swing.JLabel();
        PKP4 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        PKTP2 = new javax.swing.JLabel();
        Pekerjaan1 = new javax.swing.JLabel();
        BesarPajak1 = new javax.swing.JLabel();
        NPWP3 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        PTKP3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Hitung = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        Judul = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Judul2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 0, 153));

        Data.setBackground(new java.awt.Color(204, 255, 255));

        Nama1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Nama1.setText("Nama");
        Nama1.setToolTipText("");

        IsiNama1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        IsiNama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiNama1ActionPerformed(evt);
            }
        });

        Gaji1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Gaji1.setText("Gaji Pokok");
        Gaji1.setToolTipText("");

        IsiGaji1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        IsiGaji1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiGaji1ActionPerformed(evt);
            }
        });

        Perusahaan1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Perusahaan1.setText("Nama Perusahaan");
        Perusahaan1.setToolTipText("");

        IsiPerusahaan1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        IsiPerusahaan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiPerusahaan1ActionPerformed(evt);
            }
        });

        Status1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Status1.setText("Status Pernikahan");
        Status1.setToolTipText("");

        PilihStatus1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PilihStatus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Belum Menikah", "Sudah Menikah" }));
        PilihStatus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihStatus1ActionPerformed(evt);
            }
        });

        NPWP1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        NPWP1.setText("NPWP");
        NPWP1.setToolTipText("");

        IsiNPWP1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        IsiNPWP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiNPWP1ActionPerformed(evt);
            }
        });

        Kelamin1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Kelamin1.setText("Jenis Kelamin");
        Kelamin1.setToolTipText("");

        PilihKelamin1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PilihKelamin1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Laki-laki", "Perempuan" }));
        PilihKelamin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihKelamin1ActionPerformed(evt);
            }
        });

        Iuran1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Iuran1.setText("Jumlah Iuran");
        Iuran1.setToolTipText("");

        IsiIuran1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        IsiIuran1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiIuran1ActionPerformed(evt);
            }
        });

        Tunjangan1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Tunjangan1.setText("Jumlah Tunjangan");
        Tunjangan1.setToolTipText("");

        IsiTunjangan1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        IsiTunjangan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiTunjangan1ActionPerformed(evt);
            }
        });

        Jabatan1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Jabatan1.setText("Jabatan");
        Jabatan1.setToolTipText("");

        IsiJabatan1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        IsiJabatan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiJabatan1ActionPerformed(evt);
            }
        });

        Anak1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Anak1.setText("Jumlah Anak");
        Anak1.setToolTipText("");

        IsiAnak1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        IsiAnak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiAnak1ActionPerformed(evt);
            }
        });

        JudulData.setBackground(new java.awt.Color(0, 0, 255));
        JudulData.setForeground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("DATA WAJIB PAJAK");

        javax.swing.GroupLayout JudulDataLayout = new javax.swing.GroupLayout(JudulData);
        JudulData.setLayout(JudulDataLayout);
        JudulDataLayout.setHorizontalGroup(
            JudulDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JudulDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JudulDataLayout.setVerticalGroup(
            JudulDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JudulDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Saudara1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Saudara1.setText("Bersaudara");
        Saudara1.setToolTipText("");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel23.setText("/ Bulan");
        jLabel23.setToolTipText("");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel24.setText("/ Bulan");
        jLabel24.setToolTipText("");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel25.setText("/ Bulan");
        jLabel25.setToolTipText("");

        javax.swing.GroupLayout DataLayout = new javax.swing.GroupLayout(Data);
        Data.setLayout(DataLayout);
        DataLayout.setHorizontalGroup(
            DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jabatan1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NPWP1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nama1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Perusahaan1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Status1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Anak1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kelamin1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tunjangan1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gaji1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Iuran1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataLayout.createSequentialGroup()
                        .addComponent(JudulData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DataLayout.createSequentialGroup()
                        .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IsiPerusahaan1)
                            .addComponent(IsiJabatan1)
                            .addComponent(IsiNPWP1)
                            .addComponent(IsiNama1)
                            .addGroup(DataLayout.createSequentialGroup()
                                .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PilihStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DataLayout.createSequentialGroup()
                                        .addComponent(IsiAnak1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Saudara1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(PilihKelamin1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DataLayout.createSequentialGroup()
                                        .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(IsiTunjangan1)
                                                .addComponent(IsiGaji1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(IsiIuran1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 15, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))))
        );
        DataLayout.setVerticalGroup(
            DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JudulData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DataLayout.createSequentialGroup()
                        .addComponent(IsiNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IsiNPWP1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PilihKelamin1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IsiJabatan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IsiPerusahaan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PilihStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IsiAnak1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Saudara1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IsiGaji1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IsiTunjangan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IsiIuran1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DataLayout.createSequentialGroup()
                        .addComponent(Nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NPWP1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Kelamin1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jabatan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Perusahaan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Status1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Anak1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Gaji1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tunjangan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Iuran1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Hasil.setBackground(new java.awt.Color(204, 255, 255));

        Pekerjaan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Pekerjaan.setText("-");
        Pekerjaan.setToolTipText("");

        PKP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PKP.setText("-");
        PKP.setToolTipText("");

        Persen.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Persen.setText("-");
        Persen.setToolTipText("");

        PTKP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PTKP.setText("-");
        PTKP.setToolTipText("");

        WPajak.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        WPajak.setText("-");
        WPajak.setToolTipText("");

        Bersih.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Bersih.setText("-");
        Bersih.setToolTipText("");

        NPWP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        NPWP.setText("-");
        NPWP.setToolTipText("");

        JPajak.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        JPajak.setText("-");
        JPajak.setToolTipText("");

        JudulHasil.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("HASIL PERHITUNGAN");

        javax.swing.GroupLayout JudulHasilLayout = new javax.swing.GroupLayout(JudulHasil);
        JudulHasil.setLayout(JudulHasilLayout);
        JudulHasilLayout.setHorizontalGroup(
            JudulHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JudulHasilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JudulHasilLayout.setVerticalGroup(
            JudulHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JudulHasilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TitikDua1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TitikDua1.setText(":");
        TitikDua1.setToolTipText("");

        JPajak3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        JPajak3.setText("harus Dibayarkan");
        JPajak3.setToolTipText("");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel41.setText(":");
        jLabel41.setToolTipText("");

        Bersih1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Bersih1.setText("Penghasilan Bersih");
        Bersih1.setToolTipText("");

        PKP3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PKP3.setText("Penghasilan Kena");
        PKP3.setToolTipText("");

        WPajak1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        WPajak1.setText("Nama Wajib Pajak");
        WPajak1.setToolTipText("");

        TitikDua6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TitikDua6.setText(":");
        TitikDua6.setToolTipText("");

        TitikDua7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TitikDua7.setText(":");
        TitikDua7.setToolTipText("");

        TitikDua9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TitikDua9.setText(":");
        TitikDua9.setToolTipText("");

        JPajak1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        JPajak1.setText("Jumlah Pajak");
        JPajak1.setToolTipText("");

        TitikDua8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TitikDua8.setText(":");
        TitikDua8.setToolTipText("");

        PKP4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PKP4.setText("Pajak (PKP)");
        PKP4.setToolTipText("");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel42.setText(":");
        jLabel42.setToolTipText("");

        PKTP2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PKTP2.setText("Penghasilan Tidak");
        PKTP2.setToolTipText("");

        Pekerjaan1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Pekerjaan1.setText("Pekerjaan");
        Pekerjaan1.setToolTipText("");

        BesarPajak1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BesarPajak1.setText("Besar Pajak");
        BesarPajak1.setToolTipText("");

        NPWP3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        NPWP3.setText("NPWP");
        NPWP3.setToolTipText("");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel31.setText(":");
        jLabel31.setToolTipText("");

        PTKP3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PTKP3.setText("Kena Pajak (PTKP)");
        PTKP3.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel5.setText("*semua nominal dihitung per tahun");

        javax.swing.GroupLayout HasilLayout = new javax.swing.GroupLayout(Hasil);
        Hasil.setLayout(HasilLayout);
        HasilLayout.setHorizontalGroup(
            HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HasilLayout.createSequentialGroup()
                .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HasilLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HasilLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(JudulHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HasilLayout.createSequentialGroup()
                                .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(HasilLayout.createSequentialGroup()
                                            .addComponent(WPajak1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TitikDua6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(HasilLayout.createSequentialGroup()
                                            .addComponent(NPWP3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(HasilLayout.createSequentialGroup()
                                            .addComponent(Pekerjaan1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TitikDua1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HasilLayout.createSequentialGroup()
                                            .addComponent(Bersih1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HasilLayout.createSequentialGroup()
                                            .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(PKTP2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(PTKP3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TitikDua9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(PKP4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(HasilLayout.createSequentialGroup()
                                            .addComponent(PKP3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TitikDua7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(HasilLayout.createSequentialGroup()
                                            .addComponent(BesarPajak1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TitikDua8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HasilLayout.createSequentialGroup()
                                            .addComponent(JPajak1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(HasilLayout.createSequentialGroup()
                                            .addComponent(JPajak3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(22, 22, 22))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WPajak, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                                    .addComponent(NPWP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Pekerjaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bersih, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PTKP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PKP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Persen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JPajak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HasilLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        HasilLayout.setVerticalGroup(
            HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HasilLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JudulHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HasilLayout.createSequentialGroup()
                        .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WPajak1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TitikDua6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NPWP3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pekerjaan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TitikDua1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bersih1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PKTP2)
                            .addComponent(TitikDua9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PTKP3)
                        .addGap(18, 18, 18)
                        .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PKP3)
                            .addComponent(TitikDua7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PKP4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BesarPajak1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TitikDua8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JPajak1)
                            .addComponent(jLabel31)))
                    .addGroup(HasilLayout.createSequentialGroup()
                        .addComponent(WPajak, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NPWP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PTKP)
                        .addGap(41, 41, 41)
                        .addComponent(PKP)
                        .addGap(36, 36, 36)
                        .addComponent(Persen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JPajak)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPajak3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        Hitung.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Hitung.setText("HITUNG");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Clear.setText("CLEAR");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Keluar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Keluar.setText("KELUAR");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        Judul.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        jLabel3.setText("APIPAH");

        javax.swing.GroupLayout JudulLayout = new javax.swing.GroupLayout(Judul);
        Judul.setLayout(JudulLayout);
        JudulLayout.setHorizontalGroup(
            JudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JudulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JudulLayout.setVerticalGroup(
            JudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JudulLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Judul2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("APLIKASI PENGHITUNG PAJAK PENGHASILAN");

        javax.swing.GroupLayout Judul2Layout = new javax.swing.GroupLayout(Judul2);
        Judul2.setLayout(Judul2Layout);
        Judul2Layout.setHorizontalGroup(
            Judul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Judul2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Judul2Layout.setVerticalGroup(
            Judul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(204, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(15, 29));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(204, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(15, 15));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(Hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(342, 342, 342)
                                .addComponent(Judul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(408, 408, 408)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(311, 311, 311)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Judul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        WPajak.setText("-");
        NPWP.setText("-");
        Pekerjaan.setText("-");
        Bersih.setText("-");
        PTKP.setText("-");
        PKP.setText("-");
        Persen.setText("-");
        JPajak.setText("-");
    }//GEN-LAST:event_ClearActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        WPajak.setText(JenisKelamin+IsiNama1.getText());
        NPWP.setText(IsiNPWP1.getText());
        Pekerjaan.setText(IsiJabatan1.getText()+"  di  "+IsiPerusahaan1.getText());
        
        int Gaji, Tunjangan, Iuran, PBersih, Anak, Pribadi, Status, IsiPTKP, IsiPKP, PajakBln, PajakThn;
        
        Gaji = Integer.parseInt(IsiGaji1.getText());
        Tunjangan = Integer.parseInt(IsiTunjangan1.getText());
        Iuran = Integer.parseInt(IsiIuran1.getText());
        PBersih = (Gaji*12) + (Tunjangan*12) - (Iuran*12);
        Bersih.setText("Rp "+String.valueOf(PBersih)+" ,-");
        
        Pribadi = 54000000;
        Status = Integer.parseInt(PTKPStat);
        Anak = Integer.parseInt(IsiAnak1.getText());
        IsiPTKP = Pribadi + Status + (Anak*4500000);
        PTKP.setText("Rp "+String.valueOf(IsiPTKP)+" ,-");
        
        IsiPKP = PBersih -IsiPTKP;
        if (IsiPKP <= 0){
            PKP.setText("-");
            Persen.setText("-");
            JPajak.setText("Penghasilan Anda tidak Dikenakan Pajak");
        }
        else if (IsiPKP > 0){
            PKP.setText("Rp "+String.valueOf(IsiPKP)+" ,-");

            if (IsiPKP < 50000000){
                Persen.setText("5%");
                PajakBln = (IsiPKP * 5 / 100)/12;
                PajakThn = IsiPKP * 5 / 100;
                JPajak.setText("Rp "+String.valueOf(PajakThn)+" ,-/Thn  atau  Rp "+String.valueOf(PajakBln)+" ,-/Bln");
            }
            else if (IsiPKP > 50000000 & IsiPKP < 250000000){
                Persen.setText("15%");
                PajakBln = (IsiPKP * 15 / 100)/12;
                PajakThn = IsiPKP * 15 / 100;
                JPajak.setText("Rp "+String.valueOf(PajakThn)+" ,-/Thn  atau  Rp "+String.valueOf(PajakBln)+" ,-/Bln");
            }
            else if (IsiPKP > 250000000 & IsiPKP < 500000000){
                Persen.setText("25%");
                PajakBln = (IsiPKP * 25 / 100)/12;
                PajakThn = IsiPKP * 25 / 100;
                JPajak.setText("Rp "+String.valueOf(PajakThn)+" ,-/Thn  atau  Rp "+String.valueOf(PajakBln)+" ,-/Bln");
            }
            else if (IsiPKP > 500000000){
                Persen.setText("50%");
                PajakBln = (IsiPKP * 50 / 100)/12;
                PajakThn = IsiPKP * 50 / 100;
                JPajak.setText("Rp "+String.valueOf(PajakThn)+" ,-/Thn  atau  Rp "+String.valueOf(PajakBln)+" ,-/Bln");
            }    
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_KeluarActionPerformed

    private void IsiIuran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiIuran1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiIuran1ActionPerformed

    private void IsiNPWP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiNPWP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiNPWP1ActionPerformed

    private void PilihKelamin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihKelamin1ActionPerformed

        if (PilihKelamin1.getSelectedItem() == "Laki-laki"){
            JenisKelamin = "Bapak ";
        }
        else if (PilihKelamin1.getSelectedItem() == "Perempuan"){
            JenisKelamin = "Ibu ";
        } 
    }//GEN-LAST:event_PilihKelamin1ActionPerformed

    private void IsiPerusahaan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiPerusahaan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiPerusahaan1ActionPerformed

    private void IsiNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiNama1ActionPerformed

    private void IsiAnak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiAnak1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiAnak1ActionPerformed

    private void IsiJabatan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiJabatan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiJabatan1ActionPerformed

    private void IsiTunjangan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiTunjangan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiTunjangan1ActionPerformed

    private void IsiGaji1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiGaji1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiGaji1ActionPerformed

    private void PilihStatus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihStatus1ActionPerformed
        
        if (PilihStatus1.getSelectedItem() == "Sudah Menikah"){
            PTKPStat = "4500000";
        }
        else if (PilihKelamin1.getSelectedItem() == "Belum Menikah"){
            PTKPStat = "0";
        }
    }//GEN-LAST:event_PilihStatus1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasAkhir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasAkhir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasAkhir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasAkhir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasAkhir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anak1;
    private javax.swing.JLabel Bersih;
    private javax.swing.JLabel Bersih1;
    private javax.swing.JLabel BesarPajak1;
    private javax.swing.JButton Clear;
    private javax.swing.JPanel Data;
    private javax.swing.JLabel Gaji1;
    private javax.swing.JPanel Hasil;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField IsiAnak1;
    private javax.swing.JTextField IsiGaji1;
    private javax.swing.JTextField IsiIuran1;
    private javax.swing.JTextField IsiJabatan1;
    private javax.swing.JTextField IsiNPWP1;
    private javax.swing.JTextField IsiNama1;
    private javax.swing.JTextField IsiPerusahaan1;
    private javax.swing.JTextField IsiTunjangan1;
    private javax.swing.JLabel Iuran1;
    private javax.swing.JLabel JPajak;
    private javax.swing.JLabel JPajak1;
    private javax.swing.JLabel JPajak3;
    private javax.swing.JLabel Jabatan1;
    private javax.swing.JPanel Judul;
    private javax.swing.JPanel Judul2;
    private javax.swing.JPanel JudulData;
    private javax.swing.JPanel JudulHasil;
    private javax.swing.JLabel Kelamin1;
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel NPWP;
    private javax.swing.JLabel NPWP1;
    private javax.swing.JLabel NPWP3;
    private javax.swing.JLabel Nama1;
    private javax.swing.JLabel PKP;
    private javax.swing.JLabel PKP3;
    private javax.swing.JLabel PKP4;
    private javax.swing.JLabel PKTP2;
    private javax.swing.JLabel PTKP;
    private javax.swing.JLabel PTKP3;
    private javax.swing.JLabel Pekerjaan;
    private javax.swing.JLabel Pekerjaan1;
    private javax.swing.JLabel Persen;
    private javax.swing.JLabel Perusahaan1;
    private javax.swing.JComboBox<String> PilihKelamin1;
    private javax.swing.JComboBox<String> PilihStatus1;
    private javax.swing.JLabel Saudara1;
    private javax.swing.JLabel Status1;
    private javax.swing.JLabel TitikDua1;
    private javax.swing.JLabel TitikDua6;
    private javax.swing.JLabel TitikDua7;
    private javax.swing.JLabel TitikDua8;
    private javax.swing.JLabel TitikDua9;
    private javax.swing.JLabel Tunjangan1;
    private javax.swing.JLabel WPajak;
    private javax.swing.JLabel WPajak1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
